# Generated by Django 5.2.12 on 2026-03-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='category',
            field=models.CharField(choices=[('floor', 'Floor Tile'), ('wall', 'Wall Tile'), ('bathroom', 'Bathroom Tile'), ('kitchen', 'Kitchen Tile'), ('outdoor', 'Outdoor Tile')], max_length=100),
        ),
    ]
