# Generated by Django 5.2.12 on 2026-03-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0002_alter_tile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='category',
            field=models.CharField(choices=[('kitchen', 'Kitchen Tiles'), ('washroom', 'Washroom Tiles'), ('bedroom', 'Bedroom Tiles'), ('living', 'Living Room Tiles'), ('outdoor', 'Outdoor Tiles'), ('commercial', 'Commercial Space')], max_length=100),
        ),
    ]
