# Generated by Django 5.2.12 on 2026-03-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0004_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sanitary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('commode', 'Commode'), ('washbasin', 'Wash Basin'), ('utensil_basin', 'Utensil Basin'), ('tap', 'Tap / Toti')], max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='sanitary/')),
                ('description', models.TextField()),
            ],
        ),
    ]
