# Generated by Django 5.2.12 on 2026-03-19 13:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0005_sanitary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanitary',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
